package com.hmcr.model.clases;
// Generated 05-29-2014 10:52:59 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private int idtipousuario;
     private String nombretipousuario;
     private Set usuarios = new HashSet(0);

    public Tipousuario() {
    }

	
    public Tipousuario(int idtipousuario) {
        this.idtipousuario = idtipousuario;
    }
    public Tipousuario(int idtipousuario, String nombretipousuario, Set usuarios) {
       this.idtipousuario = idtipousuario;
       this.nombretipousuario = nombretipousuario;
       this.usuarios = usuarios;
    }
   
    public int getIdtipousuario() {
        return this.idtipousuario;
    }
    
    public void setIdtipousuario(int idtipousuario) {
        this.idtipousuario = idtipousuario;
    }
    public String getNombretipousuario() {
        return this.nombretipousuario;
    }
    
    public void setNombretipousuario(String nombretipousuario) {
        this.nombretipousuario = nombretipousuario;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


