package com.hmcr.model.clases;
// Generated 05-29-2014 10:52:59 PM by Hibernate Tools 3.6.0



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String user;
     private Tipousuario tipousuario;
     private String password;
     private String nombreusuario;
     private String apellidousuario;
     private short bloqueado;

    public Usuario() {
    }

	
    public Usuario(String user, String password, String nombreusuario, String apellidousuario, short bloqueado) {
        this.user = user;
        this.password = password;
        this.nombreusuario = nombreusuario;
        this.apellidousuario = apellidousuario;
        this.bloqueado = bloqueado;
    }
    public Usuario(String user, Tipousuario tipousuario, String password, String nombreusuario, String apellidousuario, short bloqueado) {
       this.user = user;
       this.tipousuario = tipousuario;
       this.password = password;
       this.nombreusuario = nombreusuario;
       this.apellidousuario = apellidousuario;
       this.bloqueado = bloqueado;
    }
   
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getApellidousuario() {
        return this.apellidousuario;
    }
    
    public void setApellidousuario(String apellidousuario) {
        this.apellidousuario = apellidousuario;
    }
    public short getBloqueado() {
        return this.bloqueado;
    }
    
    public void setBloqueado(short bloqueado) {
        this.bloqueado = bloqueado;
    }




}


